/* automatically generated by rust-bindgen 0.69.2 */

use super::binding_libretro::retro_log_level;

#[doc = " // essa callback deve ser criada no rust e envida para set_rs_cb"]
pub type RsCbT = ::std::option::Option<
    unsafe extern "C" fn(level: retro_log_level, log: *const ::std::os::raw::c_char),
>;

extern "C" {
    pub fn configure(rs_cb: RsCbT, core_cb: *mut ::std::os::raw::c_void);
}

extern "C" {
    pub fn deinit();
}
